[package]
name = "debug"
version = "0.1.0"
edition = "2024"

[dependencies]
hyperlane-macros = { path = "../" }
hyperlane = "*"
serde = { version = "*", features = ["derive"] }
inventory = "*"
tokio = { version = "*", features = ["full"] }
