[package]
name = "hyperlane-macros"
version = "1.8.4"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
description = """hyperlane macro"""
keywords = ["http", "request", "response", "tcp", "cross-platform"]
repository = "https://github.com/eastspire/hyperlane-macros.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "target",
    "Cargo.lock",
    "sh",
    ".github",
    "logs",
    "img",
    "**/*.log",
    "debug"
]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.104", features = ["full"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"

[dev-dependencies]
hyperlane = "5.57.1"
serde = { version = "1.0.219", features = ["derive"] }

[profile.dev]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"

[profile.release]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"
